name: Publish GH release

on:
  workflow_dispatch:
    inputs:
      description:
        description: >
          Description of this release.
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          npm ci
          npm install vsce -g
          vsce package
      
      - name: Release Name
        id: release_name
        run: |
          version=grep -oP '(?<="version": ")[^"]*' package.json
          echo "::set-output name=release-name::$version"
        
      - name: Publish GH Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.release_name.outputs.release_name }}"
          body: "${{ github.event.inputs.description }}"
          target_commitish: "${{ github.ref }}"
          tag_name: "${{ steps.release_name.outputs.release_name }}"
          files: |
            itrackhelper-${{ steps.release_name.outputs.release_name }}.vsix